# Generated by Django 2.2.7 on 2019-11-14 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('dishID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('personID', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('second_name', models.CharField(max_length=50)),
                ('phone_no', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('restaurantID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('address', models.TextField()),
                ('phone_no', models.PositiveIntegerField()),
                ('max_size', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('reservationID', models.AutoField(primary_key=True, serialize=False)),
                ('no_of_people', models.PositiveIntegerField()),
                ('date_of_booking', models.DateField()),
                ('time_of_booking', models.DateTimeField(unique=True)),
                ('Person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderID', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField()),
                ('address', models.TextField()),
                ('Dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.Dish')),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('accountID', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('Person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.Person')),
                ('Restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.Restaurant')),
            ],
        ),
    ]
