# Generated by Django 2.2.7 on 2019-11-25 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='time_of_booking',
            field=models.TimeField(unique=True),
        ),
    ]
