# Generated by Django 2.2.7 on 2019-12-07 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_auto_20191125_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='Person',
        ),
    ]
