# Generated by Django 2.2.7 on 2019-12-09 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_remove_reservation_person'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='Person',
            new_name='person',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='Dish',
            new_name='dish',
        ),
        migrations.RemoveField(
            model_name='account',
            name='Restaurant',
        ),
    ]
