# Generated by Django 2.2.7 on 2020-02-01 15:02

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_remove_restaurant_phone_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dish',
            old_name='name',
            new_name='dish_name',
        ),
        migrations.RenameField(
            model_name='dish',
            old_name='price',
            new_name='dish_price',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='address',
            new_name='order_address',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='time',
            new_name='order_time',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='address',
            new_name='rest_address',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='max_size',
            new_name='rest_max_size',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='name',
            new_name='rest_name',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='rest_phone_no',
            field=phone_field.models.PhoneField(default='', max_length=31),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone_no',
            field=phone_field.models.PhoneField(default='', max_length=31),
        ),
    ]
