# Generated by Django 2.2.7 on 2020-02-03 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_auto_20200201_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='time_of_booking',
            field=models.TimeField(),
        ),
    ]
