# Generated by Django 2.2.7 on 2020-02-03 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_auto_20200203_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='person',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='bookings.Person'),
        ),
    ]
