# Generated by Django 2.2.7 on 2020-02-21 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0011_reservation_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='additional',
            field=models.TextField(default=''),
        ),
    ]
