# Generated by Django 2.2.7 on 2020-02-03 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0011_reservation_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='person',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='bookings.Person'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='person',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='bookings.Person'),
        ),
    ]
