# Generated by Django 2.2.7 on 2020-02-21 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0012_reservation_additional'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='rest_email',
            field=models.EmailField(default='', max_length=300),
        ),
    ]
