# Generated by Django 2.2.7 on 2020-02-07 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0013_auto_20200203_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reservationID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
