# Generated by Django 2.2.7 on 2020-02-07 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0015_auto_20200207_1059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='person',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.Person'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservationID',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
