# Generated by Django 2.2.7 on 2020-02-22 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0016_auto_20200221_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='reservationID',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='restaurant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='bookings.Restaurant'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='time_of_booking',
            field=models.TimeField(unique=True),
        ),
    ]
