# Generated by Django 2.2.7 on 2020-02-22 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0017_auto_20200222_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='accountID',
        ),
        migrations.RemoveField(
            model_name='order',
            name='orderID',
        ),
        migrations.AlterField(
            model_name='account',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='bookings.Person'),
        ),
        migrations.AlterField(
            model_name='order',
            name='dish',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='bookings.Dish'),
        ),
    ]
