# Generated by Django 2.2.7 on 2020-02-23 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0017_auto_20200222_1604'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
