# Generated by Django 2.2.7 on 2020-02-07 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0018_auto_20200207_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='person',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='bookings.Person'),
        ),
    ]
