# Generated by Django 2.2.7 on 2020-02-07 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0019_auto_20200207_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.Dish'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.Person'),
        ),
    ]
