# Generated by Django 2.2.7 on 2020-02-23 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0019_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='reservation',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='bookings.Reservation'),
        ),
    ]
