# Generated by Django 2.2.7 on 2020-02-07 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0020_auto_20200207_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='reservationID',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='bookings.Person'),
        ),
    ]
