# Generated by Django 2.2.7 on 2020-02-10 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0021_auto_20200207_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='reservationID',
            field=models.AutoField(default='', primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.Person'),
        ),
    ]
