# Generated by Django 2.2.7 on 2020-02-24 18:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0021_auto_20200224_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 24, 18, 17, 46, 288109, tzinfo=utc)),
        ),
    ]
