# Generated by Django 2.2.7 on 2020-02-10 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0022_auto_20200210_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='personID',
            field=models.AutoField(default='', primary_key=True, serialize=False, unique=True),
        ),
    ]
