# Generated by Django 2.2.7 on 2020-02-24 21:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0022_auto_20200224_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='rest_menu',
            field=models.FileField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 24, 21, 43, 25, 671034, tzinfo=utc)),
        ),
    ]
