# Generated by Django 2.2.7 on 2020-02-10 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0023_auto_20200210_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='personID',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookings.Person'),
        ),
    ]
