# Generated by Django 2.2.7 on 2020-02-25 11:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0023_auto_20200224_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 25, 11, 23, 0, 252395, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date_of_booking',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='rest_menu',
            field=models.ImageField(upload_to=''),
        ),
    ]
