# Generated by Django 2.2.7 on 2020-02-25 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0025_auto_20200225_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='rest_max_size',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
