# Generated by Django 2.2.7 on 2020-02-10 20:21

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0025_auto_20200210_2000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staffID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('staff_first_name', models.CharField(max_length=50)),
                ('staff_second_name', models.CharField(max_length=50)),
                ('staff_phone_no', phone_field.models.PhoneField(default='', max_length=31)),
                ('staff_email', models.EmailField(max_length=300)),
            ],
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='person',
        ),
        migrations.AddField(
            model_name='reservation',
            name='email',
            field=models.EmailField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='first_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='reservation',
            name='phone_no',
            field=phone_field.models.PhoneField(default='', max_length=31),
        ),
        migrations.AddField(
            model_name='reservation',
            name='reservationID',
            field=models.AutoField(default='', primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='second_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
