# Generated by Django 2.2.7 on 2020-02-10 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0026_auto_20200210_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reservationID',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
