# Generated by Django 2.2.7 on 2020-02-25 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookings', '0026_auto_20200225_1124'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customerID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('second_name', models.CharField(max_length=50)),
                ('phone_no', phone_field.models.PhoneField(default='', max_length=31)),
                ('email', models.EmailField(max_length=300, unique=True)),
                ('reservation', models.OneToOneField(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='bookings.Reservation')),
            ],
        ),
        migrations.RenameModel(
            old_name='Account',
            new_name='Staff',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='staff',
            field=models.ManyToManyField(to='bookings.Staff'),
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
