# Generated by Django 2.2.7 on 2020-02-10 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0027_auto_20200210_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='second_name',
            field=models.CharField(max_length=50),
        ),
    ]
