# Generated by Django 2.2.7 on 2020-02-25 11:43

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0027_auto_20200225_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=300, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_no',
            field=phone_field.models.PhoneField(default='', max_length=31, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='additional',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='rest_email',
            field=models.EmailField(default='', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='rest_phone_no',
            field=phone_field.models.PhoneField(default='', max_length=31, null=True),
        ),
    ]
