# Generated by Django 2.2.7 on 2020-02-10 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0029_auto_20200210_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='email',
            field=models.EmailField(default='', max_length=300),
        ),
    ]
