# Generated by Django 2.2.7 on 2020-02-25 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0029_auto_20200225_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='reservation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookings.Reservation'),
        ),
        migrations.AlterField(
            model_name='order',
            name='dish',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='bookings.Dish'),
        ),
    ]
