# Generated by Django 2.2.7 on 2020-02-10 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0030_auto_20200210_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='email',
            field=models.EmailField(max_length=300),
        ),
    ]
