# Generated by Django 2.2.7 on 2020-02-25 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0030_auto_20200225_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='rest_menu',
            field=models.ImageField(blank=True, null=True, upload_to='menus'),
        ),
    ]
