# Generated by Django 2.2.7 on 2020-02-26 09:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0034_auto_20200225_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date_of_booking',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='staff',
            name='restaurant',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='bookings.Restaurant'),
        ),
    ]
